name: social_fit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_onboarding_slider: ^1.0.11
  get: ^4.6.6
  shared_preferences: ^2.2.2
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4  
  rounded_loading_button: ^2.1.0  
  google_fonts: ^6.1.0
  circular_profile_avatar: ^2.0.5
  cloud_firestore: ^4.15.2
  connectivity_plus: ^5.0.2
  firebase_storage: ^11.6.6
  image_picker: ^1.0.7
  intl: ^0.18.1
  share_plus: ^7.2.2
  enefty_icons: ^1.0.7
  multiselect_formfield: ^0.1.7
  fluentui_system_icons: ^1.1.232
  eva_icons_flutter: ^3.1.0
  flutter_advanced_drawer: ^1.3.6
  google_generative_ai: ^0.2.2
  youtube_player_flutter: ^9.0.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  http: ^1.2.1
  lottie: ^3.1.0
  fluttertoast: ^8.2.4
  ionicons: ^0.2.2
  path: ^1.9.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  pie_chart: ^5.3.2
  vertical_weight_slider: ^2.5.0
  dropdown_search: ^5.0.6
  circular_chart_flutter: ^0.0.2
  syncfusion_flutter_charts: ^22.2.5
  pedometer: ^4.0.1
  health: ^7.0.1
  device_info_plus: ^9.0.0
  permission_handler: ^11.3.1
  action_slider: ^0.7.0
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  vertical_card_pager: ^1.5.0
  horizontal_card_pager: ^1.1.1
  geolocator: ^10.0.0
  android_intent: ^2.0.2
  provider: ^6.1.2
  on_audio_query: ^2.9.0
  just_audio: ^0.9.37
  rxdart: ^0.27.7
  audio_video_progress_bar: ^2.0.2
  fl_chart: ^0.41.0
  awesome_notifications: ^0.8.2
  camera: ^0.10.5+9
  line_awesome_flutter: ^2.0.0
  camera_android: ^0.10.8+13
  google_ml_kit: ^0.16.3
  tflite: ^1.1.2  
  animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/
    -  animations/
    -  assets/img/
    -  assets/onboard/
    -  images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.otf

    - family: Wotfard
      fonts:
        - asset: assets/fonts/wotfard-regular-webfont.ttf
        - asset: assets/fonts/wotfard-semibold-webfont.ttf
          weight: 600
