// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: '',
    appId: '1:749520006694:web:421755fb09cdfd51fd80e7',
    messagingSenderId: '749520006694',
    projectId: 'social-fit-e79f1',
    authDomain: 'social-fit-e79f1.firebaseapp.com',
    storageBucket: 'social-fit-e79f1.appspot.com',
    measurementId: 'G-28NFDYBXBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: '',
    appId: '1:749520006694:android:5761a07630942c25fd80e7',
    messagingSenderId: '749520006694',
    projectId: 'social-fit-e79f1',
    storageBucket: 'social-fit-e79f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:749520006694:ios:d4921a47e9b011f7fd80e7',
    messagingSenderId: '749520006694',
    projectId: 'social-fit-e79f1',
    storageBucket: 'social-fit-e79f1.appspot.com',
    iosBundleId: 'com.example.socialFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:749520006694:ios:726550bbc1884c65fd80e7',
    messagingSenderId: '749520006694',
    projectId: 'social-fit-e79f1',
    storageBucket: 'social-fit-e79f1.appspot.com',
    iosBundleId: 'com.example.socialFit.RunnerTests',
  );
}
